### ISSUE TITLE
Add Cake Addin to Website

### ISSUE THREAD

**Issue by gep13** [mabreuortega/Cake.Tfs#1] opened 2017-12-13 21:33 UTC
Great work on getting this addin created!

This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#290

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by mabreuortega** [comment] 2017-12-18 19:20
@gep13 I'm done with the requested changes.

I also found an issue in the addins page with TFS listing twice due to a typo, the issue is also fixed in my PR.

![image](https://user-images.githubusercontent.com/6969135/34123734-8622c944-e3fe-11e7-9fd5-9c6a96800595.png)

Check this out:
https://github.com/cake-build/website/pull/460

**Closed as completed** 2017-12-18 19:20 UTC

**Comment by gep13** [comment] 2018-01-01 21:50
@mabreuortega thank you for taking care of this!
